### ISSUE TITLE
Sensible response when there is no message handler

### ISSUE THREAD

**Issue by TehShrike** [TehShrike/mannish#1]
Right now if you wait for a response to a message, and there is no message handler, you'll just wait forever.

There are a couple valid ways to think about it:
1. if there's no handler, there should be an error response
2. if there's no handler, there should be an immediate successful empty response

One way to solve this would be to add a configuration option that let you pick between those two behaviors.

Another way to solve it would be to add a configuration option that let you define a "default handler" function that would be called whenever there were no listeners defined for an event.

Note for whoever goes to add this: I'm fine with going ES6 and assuming native Promise support as part of this change.

**Comment by TehShrike** [comment]
I keep thinking of the two different cases where you would use a mediator: one where you're emitting an event and don't care if anyone's listening, and another where you're specifically requesting a piece of information and you need a response back.

The solutions I thought of in the first post would work as long as you used a different mediator for each of those two purposes, but is that necessary/desirable?

Maybe there should be two different "publish" functions, one that doesn't care whether or not there are any listeners ("emit") and another that returns an error if there are no listeners who can provide a response ("request").

Thoughts?

**Comment by saibotsivad** [comment]
After re-watching Nicholas Zakas's talk (from the README), I noticed one particular thing he said: modules should be able to "publish" (he used different words, but the same concept) and "not care if anyone is listening". It was pretty fundamental to the design pattern he was promoting.

However, if you're using publish->callback/promise as a design pattern, you probably would want to handle the case where nobody is listening. This might be a special case though? E.g. if you had something like this:

```js
mediator.publish('getDocumentById', id)
    .then(displayTheDocument)
    .catch(showAnError)
```

The case where nobody is listening for `getDocumentById` and the case where the thing listening and handling `getDocumentById` is taking too long to respond are kind of similar. So maybe it doesn't matter that nobody is listening, since you should handle the timeout anyway?

I'm still trying to wrap my head around this design pattern, but it does seem like you'd want two kinds of "publish", like you were saying, one that doesn't care and one that does.

**Comment by TehShrike** [comment]
I can understand wanting the fire-and-forget messages only - it actually reminds me of Redux actions, which are elegant and simple.  And the Redux community has spent sooooo much time figuring out how to build a request/response system on top of Redux stores.

I feel more comfortable making responses a first-class citizen here because:

1. I think the mediator pattern works really well for decoupling stateful modules, maybe even better than using dependency injection to pass stateful singletons in to every controller (like for example a "track all recent notifications" module that communicates with the server).
2. Unlike Redux, this action-centric library doesn't handle maintaining state for you anywhere, it just connects stateful bits in a decoupled manner.

It may not be perfect, but since it's so easy to replicate a fire-only mediator (event emitter or even a global redux store), I don't feel bad doubling down on the response system.

I think I'll implement the two publish types.
